highlighter: rouge
permalink: pretty
markdown: kramdown

title: Neovim
description: "vim out of the box"

news:
    name: Neovim Newsletter
    authors: Neovim Community
    url: /news
    feed: /news.xml

url: "https://neovim.io"

plugins:
    - jekyll-redirect-from
    - jekyll-mentions
    - jekyll-feed

feed:
    path: news.xml

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor/
    - sponsor-generator/
