highlighter: pygments
permalink: pretty
markdown: redcarpet

title: Neovim
description: "vim out of the box"

news:
    name: Neovim Newsletter
    authors: Neovim Community
    url: http://neovim.io/news
    feed: /news.xml

url: "http://neovim.io"

gems:
    - jekyll-redirect-from
    - jekyll-mentions

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor/
